### ISSUE TITLE
Description in Pypi is not available for timy

### ISSUE THREAD

**Issue by jcopps** [ramonsaraiva/timy#21]
Please add description in Pypi website. 
https://pypi.org/project/timy/#description

**Comment by jcopps** [comment]
And isnt this available for Python 2.7?

**Comment by ramonsaraiva** [comment]
https://pypi.org/project/timy/

**Comment by jcopps** [comment]
The description says: The author of this package has not provided a project description

**Comment by ramonsaraiva** [comment]
You can try refreshing your browser cache. :smile:

**Comment by jcopps** [comment]
Oh Yeah. I am able to see it now. Thanks for reacting quick. That now looks beautiful.
