### ISSUE TITLE
process_time vs time

### ISSUE THREAD

**Issue by rasbt** [ramonsaraiva/timy#7]
Hi there. Really like this lean approach using decorators. I am wondering though if it wouldn't be better to use [`time.process_time`](https://docs.python.org/3.6/library/time.html#time.process_time)  instead of `time.time`? Or maybe this could be toggled by another decorator function argument like `time="total"` vs `time="process"` or so. What are your thoughts on this?

**Comment by ramonsaraiva** [comment]
I agree we should switch to `pref_counter` or `process_time` instead of `time`, since we are measuring code time. Could you open a PR fixing that?

Thanks!

**Comment by rasbt** [comment]
yeah sure. will create a PR in a moment

**Comment by ramonsaraiva** [comment]
Fixed, closing it.
